# Generated by Django 4.1.2 on 2022-10-11 10:25

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=[('#FFFFFF', 'white'), ('#000000', 'black'), ('#C0C0C0', 'silver'), ('#00D678', 'green'), ('#808080', 'gray'), ('#FF0000', 'red'), ('#0000ff', 'blue'), ('#ffff00', 'yellow')])),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='MarkAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марки',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(default=None, max_length=255)),
                ('price', models.IntegerField()),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.auto')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='ModelAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.markauto')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.AddField(
            model_name='auto',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.markauto'),
        ),
        migrations.AddField(
            model_name='auto',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.modelauto'),
        ),
    ]
